### PR TITLE
Implement saving using localStorage

### LINKED ISSUE #13: Saving
Players should be able to save their progress. Going to use local storage for that, maybe save in a certain interval, or auto-save after every state update.

### PR DESCRIPTION
**Pull request by mawalu**
This should fix #13

### CODE REVIEW

**Comment by seyfahni** [comment]
Hope this gets merged and released soon...

**Comment by pbrinkmeier** [comment]
Hey you, thanks for this PR! I will look through it this weekend and merge it. I already had a first look but I think I'll move the saving code to [here](https://github.com/pbrinkmeier/tichy-clicker/blob/dev/src/client/main.js#L17), or copy it to the handler of `increment` too.

**Comment by pbrinkmeier** [comment]
People may want to reset their game at some point (e.g. when `Infinity` is reached), any ideas for that? I think I will just add a button to the "How to play" page.

**Comment by pbrinkmeier** [comment]
I moved the saving code into main.js, where all the "technical stuff" happens that has nothing to do with the game, so I don't stumble upon it next time I edit init.js or update.js (which are "business logic").

**Pull request merged**
